[package]
name = "cargo-gc"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.17.0"
clap = { version = "4.3.24", features = ["derive"] }
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
